{
 "title": "vllm dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Available vLLM instances",
   "type": "stat",
   "description": "Number of healthy vLLM instances",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(endpoint) (vllm:cpu_cache_usage_perc)",
     "legendFormat": "vLLM instances"
    }
   ]
  },
  {
   "title": "Request latency distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:e2e_request_latency_seconds_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request TTFT distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:time_to_first_token_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of running requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU KV Usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "vllm:gpu_cache_usage_perc", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Number of pending requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "vllm:num_requests_waiting", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU KV cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "vllm:gpu_prefix_cache_hit_rate", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}