apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-granite-3-0-2b-instruct
  namespace: serverless-workstream
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vllm-granite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "0%"
  template:
    metadata:
      labels:
        app: vllm-granite
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
             - matchExpressions:
                 - key: nvidia.com/gpu.product
                   operator: In
                   values:
                     - NVIDIA-L40S
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        imagePullPolicy: IfNotPresent
        command:
          - vllm
          - serve
          - "ibm-granite/granite-3.0-3b-a800m-instruct"
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
        env:
        - name: HF_HOME
          value: "/data"
        - name: XDG_CONFIG_HOME
          value: "/data/vllm"
        - name: TRITON_CACHE_DIR
          value: "/data/triton"
        - name: TORCH_HOME
          value: "/data/torch"
        - name: XDG_CACHE_HOME
          value: "/data/cache/vllm" 
        ports:
          - containerPort: 8000
            name: container-port
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 60
        resources:
          limits:
            cpu: "10"
            memory: 16Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "10"
            memory: 16Gi
            nvidia.com/gpu: "1"
        securityContext:
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: vllm-storage
            mountPath: /data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vllm-storage
          persistentVolumeClaim:
            claimName: vllm-cache-pvc2