---
# Source: vllm-stack/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi